// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    ContactForm: typeof import('./components/ContactForm.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    InputField: typeof import('./components/InputField.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextAreaField: typeof import('./components/TextAreaField.vue')['default']
  }
}
