name: Docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sref/portfolio-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=${{ secrets.CLIENT_ENV }}
            BASE_URL=${{ secrets.CLIENT_DOMAIN }}
            APP_TITLE=${{ secrets.CLIENT_APP_TITLE }}
            APP_SHORT_NAME=${{ secrets.CLIENT_APP_SHORT_NAME }}
            GITHUB_URL=${{ secrets.CLIENT_GITHUB_URL }}
            FACEBOOK_URL=${{ secrets.CLIENT_FACEBOOK_URL }}
            TWITTER_URL=${{ secrets.CLIENT_TWITTER_URL }}
            LINKEDIN_URL=${{ secrets.CLIENT_LINKEDIN_URL }}
            EMAIL=${{ secrets.CLIENT_EMAIL }}
            API_URL=${{ secrets.CLIENT_API_URL }}
            BASE_URL=${{ secrets.CLIENT_BASE_URL }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
